#!/bin/bash


nfserver=9.111.251.179

mkdir -p /bak /lsf


mount 9.111.251.179:/data /bak
mount 9.111.251.179:/lsf  /lsf

if [ -f /bak/configs/hosts ]; then
    echo "#generated by LPT"  >> /etc/hosts
    cat /bak/configs/hosts >> /etc/hosts
fi
